### ISSUE TITLE
Polybar misplacement

### ISSUE THREAD

**Issue by nuzzzen** [Manas140/dotfiles#13] opened 2022-03-08 18:50 UTC
I'm having issues with polybar on Awesome WM. The bar fails to assume correct position. In my case I tried to set the bar on top, and it kinda works but as you can see on the screenshot, it's in the middle of the way and overlaps windows.
I tried applying the polybar default and your config, both top and bottom position, but results didn't change. 

On HerbstluftWM (my prev WM) this problem doesn't exist, therefore I think this is related to the Awesome config, but can't figure out what to edit, since I'm relatively new to this WM.

The following is `bottom = false`
![polybarissue](https://user-images.githubusercontent.com/39726534/157303974-239b314c-31c1-409b-a92f-a1545eb2ef23.png)

This one is `bottom = true`
![polybottom](https://user-images.githubusercontent.com/39726534/157304903-e2f8a912-0f2b-43da-b94b-73012c333b68.png)

I can post my `rc.lua` config if needed, but I didn't change almost anything from the one in the repo. 

Hope someone can point me to the correct solution.

**Comment by Manas140** [comment] 2022-03-09 05:20
Well even with the default config it works, try running the launch.sh in the polybar config... it will restart the bar and it might work
![image](https://user-images.githubusercontent.com/64472354/157377975-372ad907-ccb2-4f15-a3b0-c8bf82187f34.png)

**Comment by nuzzzen** [comment] 2022-03-09 13:46
Tried restarting, reverting to Awesome and polybar default config, but the problem is still there. I don't know if this has to do with picom or something related.

**Comment by Manas140** [comment] 2022-03-09 14:37
Can you share the config you're using currently?

**Comment by Manas140** [comment] 2022-03-09 16:51
Ohk, try this it will start polybar again and not with awesome, as It happened to me earlier but then it just stopped, so I interpreted as if it was cause it was spawning at the same time..., if running that renders polybar at bottom of the screen, you can try spawning it with other methods instead of `spawn.with_shell()`

```
~/.config/polybar/launch.sh
```

**Comment by Manas140** [comment] 2022-03-11 11:34
Can you check if the issue is due to the config, and nothing else?

**Comment by WitherCubes** [comment] 2022-03-15 14:48
Have you removed the sections of code in your `rc.lua` to disable the default bar?

**Comment by WitherCubes** [comment] 2022-03-15 15:19
Nevermind, the issue is with polybar `3.6.1` as well as `3.6.0`. Thisi is a problem with polybar and not with the config. I do not use Manas's polybar config, but still I get the misplacement of the bar and I am not able to fix it.

**Comment by Manas140** [comment] 2022-03-15 15:53
Thanks @WitherCubes well that does helps close this issue, Moreover I must start being up to date with the changes/releases made to the programs I use...

**Closed** 2022-03-15 15:53 UTC
