### ISSUE TITLE
The installer is trying to acces files/directories that don't exist.

### ISSUE THREAD

**Issue by Ceetive** [Manas140/dotfiles#8] opened 2021-11-01 20:45 UTC
I executed install.sh and got this:
```
Copying Configs
cp: "/home/johnson/.config" is not a directory
cp: "/home/.*png" doesn't exist
Configs Copied
Copying Scripts
cp:"/home/johnson/.local/bin/." can not be made: doesn't exist
Wallpapers copied
Copying Fonts
cp:"/home/johnson/.fonts" is not a directory 
```
is this normal? or not?

**Comment by Manas140** [comment] 2021-11-02 06:09
ohh i forgot to make dir's if not available for now just make those directories and run it again i'll make a installer update soon

**Comment by Manas140** [comment] 2021-11-02 07:21
the issue is resolved in the latest commit.

**Closed by Manas140** 2021-11-02 07:21 UTC

**Comment by Ceetive** [comment] 2021-11-02 08:39
Thanks!👌
